### ISSUE TITLE
Consider working with aiohttp for mutual compatibility (ref aio-libs/aiohttp#5834)

### ISSUE THREAD

**Issue by posita** [bmerry/async-solipsism#1]
I have a more detailed write-up at aio-libs/aiohttp#5834. The short version is that replacing `aiohttp`'s `TestClient`'s event loop with `async-solipsism`'s comes up against one of `async-solipsism`'s limitations, namely: `async_solipsism.exceptions.SolipsismError: Only instances of Socket or SocketFd can be registered`. I haven't dug very far into the code to see where this best might be addressed, but I thought I'd raise the issue here, in case there was interest.

**Comment by bmerry** [comment]
Thanks for the heads-up. I'd definitely like async-solipsism to work aiohttp. When I get a chance (which might be a while unfortunately) I'll take a look at how it is creating sockets.

**Comment by bmerry** [comment]
Closing as I've released 0.3 and the README has instructions on how to test with aiohttp.
